### ISSUE TITLE
Error in `on_message`

### ISSUE THREAD

**Issue by CaedenPH** [realstealthninja/Stealthybot#9]
```py
Ignoring exception in on_message
 Traceback (most recent call last):
   File "/home/pi/.local/lib/python3.10/site-packages/disnake/client.py", line 515, in _run_event
     await coro(*args, **kwargs)
   File "/home/pi/stealthybot/cogs/activity/cog.py", line 31, in activity_listener
     await self.act_helper.select_one("Users", filter_column="")
   File "/home/pi/stealthybot/cogs/activity/activityhelpers.py", line 91, in select_one
     cur: aiosqlite.Cursor = await self.database.cursor()
 AttributeError: 'NoneType' object has no attribute 'cursor'
 Ignoring exception in on_message
 Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.10/site-packages/disnake/client.py", line 515, in _run_event
     await coro(*args, **kwargs)
   File "/home/pi/stealthybot/cogs/activity/cog.py", line 31, in activity_listener
     await self.act_helper.select_one("Users", filter_column="")
   File "/home/pi/stealthybot/cogs/activity/activityhelpers.py", line 91, in select_one
     cur: aiosqlite.Cursor = await self.database.cursor()
 AttributeError: 'NoneType' object has no attribute 'cursor'
```

**Comment by realstealthninja** [comment]
already fixed in 685358f3f57adb30a6587c0fd5755067e5b6bc9f
